### ISSUE TITLE
pytorch2onnx

### ISSUE THREAD

**Issue by onionysy** [tusen-ai/Anchor3DLane#16]
How to use pytorch2onnx.py?

**Comment by jasmine-97** [comment]
I am confused about that too. 
test_pipeline maybe is not right?

=> Loading checkpoint '/mnt/yuantiantian1/Anchor3DLane-main/che_pre/tf_efficientnet_b3_ns-9d44bf68.pth'
=> Loaded checkpoint '/mnt/yuantiantian1/Anchor3DLane-main/che_pre/tf_efficientnet_b3_ns-9d44bf68.pth'
{'type': 'Resize', 'img_scale': (480, 360), 'keep_ratio': False}
Traceback (most recent call last):
  File "pytorch2onnx.py", line 379, in <module>
    rescale_shape=rescale_shape)
  File "pytorch2onnx.py", line 85, in _prepare_input_img
    test_pipeline[1]['transforms'][0]['keep_ratio'] = False
  File "/root/anaconda3/envs/lane3d/lib/python3.7/site-packages/mmcv/utils/config.py", line 38, in __missing__
    raise KeyError(name)
KeyError: 'transforms'

**Comment by jasmine-97** [comment]
> How to use pytorch2onnx.py?

Hello, have you solved this problem? wish your reply!

**Comment by DaZhUUU** [comment]
When I run pytorch2onnx.py, it occurs an error. How can I get the onnx model?
AttributeError: 'Anchor3DLane' object has no attribute 'decode_head'

**Comment by jeonghyunjo** [comment]
> When I run pytorch2onnx.py, it occurs an error. How can I get the onnx model? AttributeError: 'Anchor3DLane' object has no attribute 'decode_head'

Currently working on exporting ONNX file and seems like decode_head is not required. Instead of that, I used mode.num_category for num_classes.
